FULL_GUIDELINES = [
    "Return a single valid JSON block. Use standardized capitalization for biomedical terms and preserve established abbreviations such as QT, ECG, DXA, REM, NREM, LAB, AHA, MRI, OCT, and BMI.",
    "Ensure that the JSON format is valid and all required fields are present. Keep explanations concise and make explanation keys match the result fields when explanations are included.",
    "`qualifier_MU` and `qualifier_MT` are internal reference fields only. Do not output them as result keys. Do not copy measurement tools or units from metadata into HAP, ORP, MM, MC, MID, SI, AS, or OT.",
    "If a qualifier has multiple values, separate them with a semicolon (;).",
    "Feature is mandatory and must answer \"what is measured?\". Qualifiers are optional constraints. Do not duplicate the same semantic content in both Feature and Qualifier.",
    "Use the boundary test: if removing a word still preserves the core measurable object/property, put that word into a Qualifier; if removing it makes the Feature too vague, keep it in the Feature.",
    "A feature is the minimal biologically meaningful unit. For example, \"thickness\" is too vague, while \"optic disc layer thickness\", \"macular thickness\", or \"arm length\" is appropriate.",
    "For questionnaire-based phenotypes with long or conversational names, summarize the feature concisely based on semantics while retaining relevant qualifier information.",
    "The Top class, Subclass, Sample Type (ST), Measurement Tool (MT), and Measurement Unit (MU) in metadata must not be included in HAP, ORP, MM, MC, MID, SI, AS, or OT.",
    "Decision order for result/process terms: statistical summary words go to SI; timing/frequency/state/setting/task conditions go to MC; measured dimensions/components/channels/questionnaire item categories go to MID; standardized protocols/formulas/segmentation rules go to MM.",
    "Measurement methods (MM) are standardized procedures, protocols, operation rules, segmentation rules, or computational formulas. Do not put instruments such as OCT, MRI, DXA, ECG, or questionnaire names into MM when they are tools.",
    "Do not put software packages, atlases, image-processing libraries, texture-matrix families, or feature extraction tool names into MM unless the term explicitly describes them as the measurement operation.",
    "For retinal ring/sector methods, use canonical MM terms such as \"36 Equal Part Of Ring\", \"12 Equal Part Of Ring\", \"6 Equal Part Of Ring\", or \"4 Equal Part Of Ring\".",
    "Measurement conditions (MC) include time windows, frequency, environment, subject state, task condition, zone, panel, region setting, and instrument parameters. Questionnaire time windows such as \"in the past week\" belong to MC.",
    "Normalize numbered region settings in MC: \"zone 05\", \"zone 06\", or \"zone 30\" should be output as \"Zone\" unless the exact number is essential.",
    "Use MC for measurement context terms such as \"total\", \"outer layer\", \"deep layer\", \"superficial layer\", \"end diastole\", \"diastole\", \"awake state\", REM sleep, NREM sleep, sleep stages, and \"if deceased\" when these words define the state, layer, phase, or condition under which the measurement is made.",
    "Measurement indicators (MID) are specific measured result dimensions, components, channels, sub-indicators, or questionnaire item categories, such as \"principal component\", \"LAB value\", \"skin area\", \"forward scatter\", \"wine\", \"herbal tea\", or \"low-alcohol baijiu\".",
    "For numbered principal components, output the canonical MID \"Principal Component\" only.",
    "Do not put anatomical parts, digit labels, metacarpal names, ring finger, layer names, region labels, or plain numeric codes into MID unless they are explicitly the measured result dimension.",
    "For normal range boundaries, put \"Upper Limit\" or \"Lower Limit\" into MID rather than SI.",
    "Statistical indicators (SI) include \"average\", \"maximum\", \"minimum\", \"median\", \"percentile\", \"standard deviation\", \"difference\", \"ratio\", \"count\", and \"z-score\". Use \"average\" rather than \"mean\".",
    "Do not classify \"upper limit\" or \"lower limit\" as SI when it means a clinical/reference range boundary.",
    "The qualifier_MC does not contain demographic-related information; information such as age, sex, disease group, target population, family relationship, smoker, drinker, tea drinker, or disease status belongs to qualifier_AS.",
    "For lifestyle questionnaire terms, infer AS from the applicable behavior: alcohol amount/frequency/age at initiation or cessation -> Drinker; smoking amount/frequency/age at initiation or cessation -> Smoker; tea concentration or amount/frequency -> Tea Drinker; coffee amount/frequency -> Coffee Drinker. Gynecological, vaginal, cervical, or pregnancy-related phenotypes usually have AS \"Female\".",
    "Feature_class rule: standardized cognitive or behavioral task/test scores, including CANTAB-like tasks such as IED, SOC, SWM, PAL, and RVP, should be classified as Questionnaire measurement. Laboratory or specimen-based examination of cells, blood, urine, pathogens, or exfoliated cells should be Ex_vivo measurement.",
    "When a phenotype involves multiple anatomical parts, especially those with a hierarchical relationship, split them into separate HAP qualifiers.",
    "The qualifier_HAP does not include sample type and directions. \"Left hand\" should use \"Hand\" for HAP and \"Left\" for ORP.",
    "Prefer specific anatomical landmark terms over broad body parts when the term names a landmark.",
    "Feature should remain a concise controlled noun phrase. Do not move reference range boundaries, subject groups, time windows, zones, methods, or questionnaire item categories into Feature when they can be represented as Qualifiers.",
    "Split compound ORP expressions into atomic values: \"superior temporal\" -> \"Superior;Temporal\", \"inferior nasal\" -> \"Inferior;Nasal\", \"left nasal superior\" -> \"Left;Nasal;Superior\".",
    "Use exactly \"not applicable\" for empty qualifier fields. If the phenotype applies to all populations without special requirements, set qualifier_AS to \"not applicable\".",
    "Use singular nouns when possible. Remove parenthetical abbreviations when they do not change meaning.",
    "Use standardized unit spacing in qualifier values: write \"1 kHz\", \"0.25 kHz\", and \"3 mm\".",
    "Use qualifier_OT only when the information cannot be assigned to HAP, ORP, MM, MC, MID, SI, or AS.",
    "If a qualifier is marked as \"not applicable\", the corresponding explanation should also be \"not applicable\".",
    "Ensure explanations are concise and standardized. The total character count of all explanations combined should not exceed 1400 characters.",
]
